### ISSUE TITLE
Cannot npm install or yarn add

### ISSUE THREAD

**Issue by huyennguyen11tiki** [mittwald/vaulTS#26]
Seems like the npm packages is removed or set to private, I cannot find it in your profile
https://www.npmjs.com/~mhelmich-mittwald
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@mittwald%2fvaults - Not found
npm ERR! 404 
npm ERR! 404  '@mittwald/vaults@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by solomonope** [comment]
I am having the same issue, any chance you can re publish anytime soon?

**Comment by rauldel** [comment]
Hello @huyennguyen11tiki  and @solomonope ,
according to [Vault's official documentation](https://www.vaultproject.io/api/libraries#node-js), this package is only available in Github Package Registry.

So, you may want to create a .npmrc file for fetching `mittwald` scoped packages from Github registry instead of NPM

The contents of your file should look like:
```
//npm.pkg.github.com/:_authToken=<a_token_generated_from_your_github_account>
@mittwald:registry=https://npm.pkg.github.com
```

Check this [Github's doc](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-to-github-packages) for extra info.

Hope it helps

**Comment by martin-helmich** [comment]
@rauldel is entirely correct, this package is published using Github's NPM registry only.

See the [release page](https://github.com/mittwald/vaulTS/packages/256193) for more information on this specific package, and have a look at [Github's documentation](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#installing-a-package) on how to install packages from their registry.
